---
workers: 5
base_url: "<required>"
integration_id: "<required>"
private_key: "<required>"
webhook_secret: "<required>"
webhack_username: "<required>"
webhack_password: "<required>"

log_ratelimit: false
debug: false
flush_redis_on_startup: false

required_approvals:
  default: 1
  -@master: 2

branch_protection_enforce_admins:
  default: false

branch_protection_contexts:
  default:
    - continuous-integration/travis-ci
