---
context: pastamaker
workers: 5
base_url: "<required>"
integration_id: "<required>"
private_key: "<required>"
webhook_secret: "<required>"
webhack_username: "<required>"
webhack_password: "<required>"

log_ratelimit: false
debug: false
flush_redis_on_startup: false
